<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Api_doc extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Api_doc_model');
        $this->load->library('form_validation');
    }

    public function index()
    {

        $data['list'] = $this->Api_doc_model->get_all();
        $this->template->load('template', 'api_doc/tbl_menu_api_list', $data);
    }
}

/* End of file Tbl_menu_api.php */
/* Location: ./application/controllers/Tbl_menu_api.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-09 15:37:36 */
/* http://harviacode.com */