<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_direktorat extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        //is_login();
        $this->load->model('M_direktorat_model');
        $this->load->library('form_validation');}

    public function index()
    {
        $method = $_SERVER['REQUEST_METHOD'];
        if ($method != 'GET') {
            $this->output->set_content_type('application/json');
            $this->output->set_status_header(400);
            $this->output->set_output(json_encode(array('status' => 400, 'message' => 'Bad request.')));
        } else {
            $cekAuthClient = $this->M_auth->checkAuthClient();
            if ($cekAuthClient == true) {
                $auth = $this->M_auth->auth();
                if ($auth['status'] == 200) {
                    $row = $this->M_direktorat_model->getAll();
                    $this->output->set_content_type('application/json');
                    $this->output->set_status_header($auth['status']);
                    $this->output->set_output(json_encode(array('status' => $auth['status'], 'message' => $row)));
                }
            }
        }
    }

    public function by_param($field,$value)
    {
        $method = $_SERVER['REQUEST_METHOD'];
        if ($method != "GET") {
            $this->output->set_content_type('application/json');
            $this->output->set_status_header(400);
            $this->output->set_output(json_encode(array('status' => 400, 'message' => 'Bad request.')));
        } else {
            $cekAuthClient = $this->M_auth->checkAuthClient();
            if ($cekAuthClient == true) {
                $auth = $this->M_auth->auth();
                if ($auth["status"] == 200) {
                    $row = $this->M_direktorat_model->getDetail($field,$value);
                    $this->output->set_content_type('application/json');
                    $this->output->set_status_header($auth["status"]);
                    $this->output->set_output(json_encode(array('status' => $auth["status"], 'message' => $row)));
                }
            }
        }
    }

}

/* End of file M_direktorat.php */
/* Location: ./application/controllers/M_direktorat.php */
/* Please DO NOT modify this information : */
/* Generated by Rifai | Codeigniter API Generator 2021-07-10 15:41:53 */
/* rifai.kre@gmail.com */