<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Zx_t_indikator_pelayanan_rs_v1_model extends CI_Model
{

    public $table = 'zx_t_indikator_pelayanan_rs_v1';
    public $id = 'id';
    public $order = 'DESC';


    // get all
    public function getAll()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    public function getDetail($field, $value)
    {
        $this->db->where($this->$field, $value);
        return $this->db->get($this->table)->result();
    }

    // public function getDetail($id)
    // {
    //     return $this->db->select('*')->from('zx_t_indikator_pelayanan_rs_v1')->where('id', $id)->get()->row();
    // }

    // public function getDetail($id)
    // {
    //     $this->db->where($this->id, $id);
    //     return $this->db->get($this->table)->row();
    // }

    public function create($data)
    {
        $this->db->insert($this->table, $data);
        return array('status' => 201, 'message' => 'Data berhasil dibuat');
    }

    public function update($data, $id)
    {
        $this->db->where($this->id, $id)->update($this->table, $data);
        return array('status' => 201, 'message' => 'Data berhasil diupdate');
    }

    public function delete($id)
    {
        $this->db->where($this->id, $id)->delete($this->table);
        //return array('status' => 201, 'message' => 'Data has been deleted');
        if ($this->db->affected_rows() > 0) {
            return array('status' => 201, 'message' => 'Data berhasil dihapus');
        } else {
            return array('status' => 201, 'message' => 'Data tidak tersedia');
        }
    }
}


/* End of file Zx_t_indikator_pelayanan_rs_v1_model.php */
/* Location: ./application/models/Zx_t_indikator_pelayanan_rs_v1_model.php */
/* Please DO NOT modify this information : */
/* Generated by Rifai | Codeigniter API Generator 2021-10-19 05:11:46 */
/* rifai.kre@gmail.com */