<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_pegawai_model extends CI_Model
{

    public $table = 'zx_m_pegawai';
    public $id = 'id_pegawai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // function fetch_pegawai($id_pegawai)
    // {
    //     $this->db->select('a.id_pegawai, b.kode_unit');
    //     $this->db->from('zr_t_rekep_iki_iku a');
    //     $this->db->join('zr_m_pegawai b', 'a.kode_unit = b.kode_unit', 'left');
    //     $this->db->where('id_pegawai', $id_pegawai);
    //     // $this->db->where('KODE_JABATAN',$KODE_JABATAN);
    //     $query = $this->db->get();
    //     foreach ($query->result() as $row) {
    //         $hasil = array(
    //             'id_pegawai' => $row->id_pegawai,
    //             'kode_unit' => $row->kode_unit,

    //         );
    //     }
    //     return $hasil;
    // }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_pegawai', $q);
        $this->db->or_like('nip', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('id_absen', $q);
        $this->db->or_like('aktif', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->or_like('user', $q);
        $this->db->or_like('create_date', $q);
        $this->db->or_like('update_date', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pegawai', $q);
        $this->db->or_like('nip', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('id_absen', $q);
        $this->db->or_like('aktif', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->or_like('user', $q);
        $this->db->or_like('create_date', $q);
        $this->db->or_like('update_date', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file M_pegawai_model.php */
/* Location: ./application/models/M_pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-04 14:19:40 */
/* http://harviacode.com */