<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rasio_optimal_kas_model extends CI_Model
{

    public $table = 'rasio_optimal_kas';
    public $id = 'no_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        // $this->datatables->select('no_id,kode,tanggal,pdptn_bunga_atas_pnglolan_kas,saldo_rekening_pnglolaan_kas,saldo_rekening_oprsnl,rasio_optimal_kas,f8,f9');
        $this->datatables->select('no_id,kode,tanggal,pdptn_bunga_atas_pnglolan_kas,saldo_rekening_pnglolaan_kas,saldo_rekening_oprsnl,rasio_optimal_kas');
        $this->datatables->from('rasio_optimal_kas');
        //add this line for join
        //$this->datatables->join('table2', 'rasio_optimal_kas.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('rasio_optimal_kas/read/$1'),'<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-xs'))."
            ".anchor(site_url('rasio_optimal_kas/update/$1'),'<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-xs'))."
                ".anchor(site_url('rasio_optimal_kas/delete/$1'),'<i class="fal fa-trash" aria-hidden="true"></i>','class="btn btn-danger btn-xs" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'no_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('pdptn_bunga_atas_pnglolan_kas', $q);
	$this->db->or_like('saldo_rekening_pnglolaan_kas', $q);
	$this->db->or_like('saldo_rekening_oprsnl', $q);
	$this->db->or_like('rasio_optimal_kas', $q);
	// $this->db->or_like('f8', $q);
	// $this->db->or_like('f9', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('pdptn_bunga_atas_pnglolan_kas', $q);
	$this->db->or_like('saldo_rekening_pnglolaan_kas', $q);
	$this->db->or_like('saldo_rekening_oprsnl', $q);
	$this->db->or_like('rasio_optimal_kas', $q);
	// $this->db->or_like('f8', $q);
	// $this->db->or_like('f9', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Rasio_optimal_kas_model.php */
/* Location: ./application/models/Rasio_optimal_kas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-10-18 09:05:24 */
/* http://harviacode.com */