<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rasio_pobo_model extends CI_Model
{

    public $table = 'rasio_pobo';
    public $id = 'no_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('no_id,kode,tanggal,pobo_total_pendapatan,pobo_pendapatan_apbn,pobo_total_beban,pobo_beban_susut_amor,rasio_pobo');
        $this->datatables->from('rasio_pobo');
        //add this line for join
        //$this->datatables->join('table2', 'rasio_pobo.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('rasio_pobo/read/$1'),'<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-xs'))." 
            ".anchor(site_url('rasio_pobo/update/$1'),'<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-xs'))." 
                ".anchor(site_url('rasio_pobo/delete/$1'),'<i class="fal fa-trash" aria-hidden="true"></i>','class="btn btn-danger btn-xs" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'no_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('pobo_total_pendapatan', $q);
	$this->db->or_like('pobo_pendapatan_apbn', $q);
	$this->db->or_like('pobo_total_beban', $q);
	$this->db->or_like('pobo_beban_susut_amor', $q);
	$this->db->or_like('rasio_pobo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('pobo_total_pendapatan', $q);
	$this->db->or_like('pobo_pendapatan_apbn', $q);
	$this->db->or_like('pobo_total_beban', $q);
	$this->db->or_like('pobo_beban_susut_amor', $q);
	$this->db->or_like('rasio_pobo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Rasio_pobo_model.php */
/* Location: ./application/models/Rasio_pobo_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-10-20 03:28:00 */
/* http://harviacode.com */