<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_kes_sdm_tenaga_bidan_model extends CI_Model
{

    public $table = 't_kes_sdm_tenaga_bidan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,tgl_transaksi,pns,pppk,anggota,non_pns_tetap,kontrak,message,user,create_date');
        $this->datatables->from('t_kes_sdm_tenaga_bidan');
        //add this line for join
        //$this->datatables->join('table2', 't_kes_sdm_tenaga_bidan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t_kes_sdm_tenaga_bidan/read/$1'),'<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-xs'))." 
            ".anchor(site_url('t_kes_sdm_tenaga_bidan/update/$1'),'<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-xs'))." 
                ".anchor(site_url('t_kes_sdm_tenaga_bidan/delete/$1'),'<i class="fal fa-trash" aria-hidden="true"></i>','class="btn btn-danger btn-xs" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tgl_transaksi', $q);
	$this->db->or_like('pns', $q);
	$this->db->or_like('pppk', $q);
	$this->db->or_like('anggota', $q);
	$this->db->or_like('non_pns_tetap', $q);
	$this->db->or_like('kontrak', $q);
	$this->db->or_like('message', $q);
	$this->db->or_like('user', $q);
	$this->db->or_like('create_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tgl_transaksi', $q);
	$this->db->or_like('pns', $q);
	$this->db->or_like('pppk', $q);
	$this->db->or_like('anggota', $q);
	$this->db->or_like('non_pns_tetap', $q);
	$this->db->or_like('kontrak', $q);
	$this->db->or_like('message', $q);
	$this->db->or_like('user', $q);
	$this->db->or_like('create_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_kes_sdm_tenaga_bidan_model.php */
/* Location: ./application/models/T_kes_sdm_tenaga_bidan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-04-11 08:44:41 */
/* http://harviacode.com */