<?php

$string = "<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class " . $m . " extends CI_Model
{

    public \$table = '$table_name';
    public \$id = '$pk';
    public \$order = 'DESC';
    ";


if ($jenis_api <> 'view') {
    $string .= "\n\n    // get all
        public function getAll()
        {
            \$this->db->order_by(\$this->id, \$this->order);
            return \$this->db->get(\$this->table)->result();
        }

        public function getDetail(\$field,\$value)
        {
            \$this->db->where(\$field, \$value);
            return \$this->db->get(\$this->table)->result();
        }

        public function create(\$data)
        {
            \$this->db->insert(\$this->table, \$data);
            return array('status' => 201, 'message' => 'Data berhasil dibuat');
        }

        public function update(\$data, \$id)
        {
            \$this->db->where(\$this->id, \$id)->update(\$this->table, \$data);
            return array('status' => 201, 'message' => 'Data berhasil diupdate');
        }

        public function delete(\$id)
        {
            \$this->db->where(\$this->id, \$id)->delete(\$this->table);
            //return array('status' => 201, 'message' => 'Data has been deleted');
            if (\$this->db->affected_rows() > 0) {
                return array('status' => 201, 'message' => 'Data berhasil dihapus');
            } else {
                return array('status' => 201, 'message' => 'Data tidak tersedia');
            }
        }";
} else {
    $string .= "\n\n    // get all
        public function getAll()
        {
            \$this->db->order_by(\$this->id, \$this->order);
            return \$this->db->get(\$this->table)->result();
        }

        public function getDetail(\$field,\$value)
        {
            \$this->db->where(\$field, \$value);
            return \$this->db->get(\$this->table)->result();
        }";
}

$string .= "\n\n}";
$string .= "\n\n
/* End of file $m_file */
/* Location: ./application/models/$m_file */
/* Please DO NOT modify this information : */
/* Generated by Rifai | Codeigniter API Generator " . date('Y-m-d H:i:s') . " */
/* rifai.kre@gmail.com */";




$hasil_model = createFile($string, $target . "models/" . $m_file);
